apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-variables
  namespace: workflow
data:
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "bandi-docker.jfrog.io/workflow-service"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "dev"
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://workflow:workflowpassword@localhost:5432/workflow"
    AIRFLOW__KUBERNETES__KUBE_CLIENT_REQUEST_ARGS: ""
    AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: workflow
    AIRFLOW__KUBERNETES__WORKER_PODS_CREATION_BATCH_SIZE: "3"
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
    AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF: airflow-variables
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    AIRFLOW__KUBERNETES__NAMESPACE: "workflow"
    #AIRFLOW__SCHEDULER__RUN_DURATION: 3600