apiVersion: v1
kind: Pod
metadata:
  labels: {}
spec:
  containers:
  - args: []
    command: []
    env:
    - name: AIRFLOW__CORE__EXECUTOR
      value: LocalExecutor
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      value: {{AIRFLOW__CORE__SQL_ALCHEMY_CONN}}
    envFrom:
    - configMapRef:
        name: airflow-variables
    image: bandi-docker.jfrog.io/workflow-service:latest
    imagePullPolicy: IfNotPresent
    name: base
    ports: []
    volumeMounts:
    - mountPath: /opt/airflow/logs
      name: airflow-logs
  hostNetwork: false
  imagePullSecrets: []
  initContainers: []
  nodeSelector: {}
  restartPolicy: Never
  securityContext:
    runAsUser: 50000
  serviceAccountName: workflow
  volumes:
  - emptyDir: {}
    name: airflow-logs